---
title: "heavy drinker"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(BMA)
library(dplyr)
library(knitr)
library(MASS)
library(xtable)
library(gtools)
```

# 1993, females
```{r}
load("df_1993.rdata")
df = df[df$drinks_binary == 1,]
df = df[df$gender == 1,]
df$heavy_drinker = ifelse(df$num_of_drinks >= 35, 1, 0)
df_ref <- df %>% dplyr::select(-c(drinks_binary, gender, num_of_drinks, age_15_17,
                                  on_housing, no_roommate, school_disc_never,
                                  somewhat_happy, single, religion_none, max_parent_edu_DK,
                                  other, relationship))

des_mat = model.matrix(lm(heavy_drinker ~ ., data = df_ref))
des_mat <- des_mat[, -1]
des_mat <- cbind(heavy_drinker = df_ref$heavy_drinker, des_mat)
des_mat <- as.data.frame(des_mat)

model_stepwise <- glm(formula = heavy_drinker ~., data = des_mat,
                      family = "binomial") %>% stepAIC(trace = FALSE)
save(model_stepwise, file="model_stepwise_female_1993.rdata")
summary(model_stepwise)

odds_mean<- exp(summary(model_stepwise)$coefficients[, "Estimate"])
odds_lb <- exp(-1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
odds_ub <- exp(1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
sig_level <- stars.pval(summary(model_stepwise)$coefficients[,4])
xtable(cbind.data.frame("Lower bound" = odds_lb, "Mean" = odds_mean, "Upper bound" = odds_ub,
                        "Significance level" = sig_level))
```

# 1993, males
```{r}
load("df_1993.rdata")
df = df[df$drinks_binary == 1,]
df = df[df$gender == 0,]
df$heavy_drinker = ifelse(df$num_of_drinks >= 65, 1, 0)
df_ref <- df %>% dplyr::select(-c(drinks_binary, gender, num_of_drinks, age_15_17,
                                  on_housing, no_roommate, school_disc_never,
                                  somewhat_happy, single, religion_none, max_parent_edu_DK,
                                  other, relationship))

des_mat = model.matrix(lm(heavy_drinker ~ ., data = df_ref))
des_mat <- des_mat[, -1]
des_mat <- cbind(heavy_drinker = df_ref$heavy_drinker, des_mat)
des_mat <- as.data.frame(des_mat)

model_stepwise <- glm(formula = heavy_drinker ~., data = des_mat,
                      family = "binomial") %>% stepAIC(trace = FALSE)
save(model_stepwise, file="model_stepwise_male_1993.rdata")
summary(model_stepwise)

odds_mean<- exp(summary(model_stepwise)$coefficients[, "Estimate"])
odds_lb <- exp(-1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
odds_ub <- exp(1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
sig_level <- stars.pval(summary(model_stepwise)$coefficients[,4])
xtable(cbind.data.frame("Lower bound" = odds_lb, "Mean" = odds_mean, "Upper bound" = odds_ub,
                        "Significance level" = sig_level))
```

# 2001, females
```{r}
load("df_2001.rdata")
df = df[df$drinks_binary == 1,]
df = df[df$gender == 1,]
df$heavy_drinker = ifelse(df$num_of_drinks >= 35, 1, 0)
df_ref <- df %>% dplyr::select(-c(drinks_binary, gender, num_of_drinks, age_15_17,
                                  on_housing, no_roommate, school_disc_never,
                                  somewhat_happy, single, religion_none, max_parent_edu_DK,
                                  other, relationship))

des_mat = model.matrix(lm(heavy_drinker ~ ., data = df_ref))
des_mat <- des_mat[, -1]
des_mat <- cbind(heavy_drinker = df_ref$heavy_drinker, des_mat)
des_mat <- as.data.frame(des_mat)

model_stepwise <- glm(formula = heavy_drinker ~., data = des_mat,
                      family = "binomial") %>% stepAIC(trace = FALSE)
save(model_stepwise, file="model_stepwise_female_2001.rdata")
summary(model_stepwise)

odds_mean<- exp(summary(model_stepwise)$coefficients[, "Estimate"])
odds_lb <- exp(-1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
odds_ub <- exp(1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
sig_level <- stars.pval(summary(model_stepwise)$coefficients[,4])
xtable(cbind.data.frame("Lower bound" = odds_lb, "Mean" = odds_mean, "Upper bound" = odds_ub,
                        "Significance level" = sig_level))
```

# 2001, males
```{r}
load("df_2001.rdata")
df = df[df$drinks_binary == 1,]
df = df[df$gender == 0,]
df$heavy_drinker = ifelse(df$num_of_drinks >= 65, 1, 0)
df_ref <- df %>% dplyr::select(-c(drinks_binary, gender, num_of_drinks, age_15_17,
                                  on_housing, no_roommate, school_disc_never,
                                  somewhat_happy, single, religion_none, max_parent_edu_DK,
                                  other, relationship))

des_mat = model.matrix(lm(heavy_drinker ~ ., data = df_ref))
des_mat <- des_mat[, -1]
des_mat <- cbind(heavy_drinker = df_ref$heavy_drinker, des_mat)
des_mat <- as.data.frame(des_mat)

model_stepwise <- glm(formula = heavy_drinker ~., data = des_mat,
                      family = "binomial") %>% stepAIC(trace = FALSE)
save(model_stepwise, file="model_stepwise_male_2001.rdata")
summary(model_stepwise)

odds_mean<- exp(summary(model_stepwise)$coefficients[, "Estimate"])
odds_lb <- exp(-1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
odds_ub <- exp(1.96 * summary(model_stepwise)$coefficients[, "Std. Error"] +
                 summary(model_stepwise)$coefficients[, "Estimate"])
sig_level <- stars.pval(summary(model_stepwise)$coefficients[,4])
xtable(cbind.data.frame("Lower bound" = odds_lb, "Mean" = odds_mean, "Upper bound" = odds_ub,
                        "Significance level" = sig_level))
```
